name: Deploy URL Shortener

on:
  push:
    branches: [main, develop]

env:
  AWS_REGION: us-east-1
  TF_VAR_environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
          
      - name: Package Lambda functions
        run: |
          zip -r ../create-url.zip create-url.*
          zip -r ../redirect-url.zip redirect-url.*
        working-directory: dist
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Terraform Init
        run: terraform init
        working-directory: infra/terraform-deployments
        
      - name: Terraform Plan
        run: | 
          # Ensure the workspace exists or create it
          terraform workspace select -or-create=true ${{ env.TF_VAR_environment }}
          terraform plan -var-file="${{ env.TF_VAR_environment }}.tfvars" -out=tfplan
        working-directory: infra/terraform-deployments
        
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        run: | 
          # Ensure the workspace exists or create it
          terraform workspace select -or-create=true ${{ env.TF_VAR_environment }}
          terraform apply -auto-approve --var-file="${{ env.TF_VAR_environment }}.tfvars" tfplan
        working-directory: infra/terraform-deployments